@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}'
String imgTag  = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: "oracle/release/" + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/fluent-bit-base:' + imgTag): 'olcne/fluent-bit-base:' + imgTag],
        architectures: ['x86_64', 'aarch64'],
        platforms: ['ol9'],
        yumOL9Repos: ['ol9_codeready_builder']
)
